---
title: 如何进行中介与调节效应分析
author: yuanbo
date: '2017-06-17'
slug: how-to-run-meditation-modration
categories: []
tags: []
---

最近分析实验数据，用到中介与调节效应分析，在此总结下如何在 spss 和 R 中进行中介与调节效应分析，以及如何在论文中报告中介与调节效应。

## 中介效应

中介效应是指变量间的影响关系（X→Y）不是直接的因果链关系而是通过一个或一个以上变量(M)的间接影响产生的，此时我们称M为中介变量，而X通过M对Y产生的的间接影响称为中介效应。在心理学研究当中，变量间的关系很少是直接的，更常见的是间接影响，许多心理自变量可能要通过中介变量产生对因变量的影响，而这常常被研究者所忽视。

以最简单的三变量为例，假设所有的变量都已经中心化，则中介关系可以用回归方程表示如下：
 1) Y=cx+e1                          
 2) M=ax+e2                           
 3) Y=c’x+bM+e3                      
上述3个方程模型图及对应方程如下：


### 中介效应检验方法

中介效应的检验传统上有三种方法，分别是依次检验法、系数乘积项检验法和差异检验法，下面简要介绍下这三种方法：

1. 依次检验法（causual steps）。依次检验法分别检验上述1）2）3）三个方程中的回归系数，程序如下：

1.1首先检验方程1）y=cx+ e1，如果c显著（H0:c=0被拒绝），则继续检验方程2），如果c不显著（说明X对Y无影响），则停止中介效应检验；
1.2 在c显著性检验通过后，继续检验方程2）M=ax+e2，如果a显著（H0:a=0被拒绝），则继续检验方程3）；如果a不显著，则停止检验；
1.3在方程1）和2）都通过显著性检验后，检验方程3）即y=c’x + bM + e3,检验b的显著性，若b显著（H0:b=0被拒绝）,则说明中介效应显著。此时检验c’,若c’显著，则说明是不完全中介效应；若不显著，则说明是完全中介效应，x对y的作用完全通过M来实现。
评价:依次检验容易在统计软件中直接实现，但是这种检验对于较弱的中介效应检验效果不理想，如a较小而b较大时，依次检验判定为中介效应不显著，但是此时ab乘积不等于0，因此依次检验的结果容易犯第二类错误（接受虚无假设即作出中介效应不存在的判断）。

2.系数乘积项检验法(products of coefficients)。此种方法主要检验ab乘积项的系数是否显著，检验统计量为z = ab/ sab，实际上熟悉统计原理的人可以看出，这个公式和总体分布为正态的总体均值显著性检验差不多，不过分子换成了乘积项，分母换成了乘积项联合标准误而已，而且此时总体分布为非正态，因此这个检验公式的Z值和正态分布下的Z值检验是不同的，同理临界概率也不能采用正态分布概率曲线来判断。具体推导公式我就不多讲了，大家有兴趣可以自己去看相关统计书籍。分母sab的计算公式为：sab=，在这个公式中，sb2和sa2分别为a和b的标准误，这个检验称为sobel检验，当然检验公式不止这一种例如Goodman I检验和Goodman II检验都可以检验（见下）,但在样本比较大的情况下这些检验效果区别不大。在AMOS中没有专门的soble检验的模块，需要自己手工计算出而在lisrel里面则有，其临界值为zα/2>0.97或zα/2<-0.97(P <0.05，N≧200)。关于临界值比率表见附件（虚无假设概率分布见MacKinnon表中无中介效应C.V.表，双侧概率，非正态分布。这个临界表没有直接给出.05的双侧概率值，只有.04的双侧概率值；以N=200为例，.05的双侧概率值在其表中大概在±0.90左右，而不是温忠麟那篇文章中提出的0.97。关于这一点，我看了温的参考文献中提到的MacKinnon那篇文章，发现温对于.97的解释是直接照搬MacKinnon原文中的一句话<For example, the empirical critical value is .97 for the .05 significance level rather than 1.96 for the standard normal test of ab 4 0. We designate this test statistic by z8 because it uses a different distribution than the normal distribution.>，实际上在MacKinnon的概率表中，这个.97的值是在N=200下对应的.04概率的双侧统计值，而不是.05概率双侧统计值，因为在该表中根本就没有直接给出.05概率的统计值。为了确定这点，我专门查了国外对这个概率表的介绍，发现的确如此，相关文章见附件mediationmodels.rar。当然，从统计概率上来说，大于0.97在这个表中意味着其值对应概率大于.05，但是当统计值小于0.9798th时而大于0.8797th，其值对应概率的判断就比较麻烦了，此时要采用0.90作为P<.05的统计值来进行判断。之所以对温的文章提出质疑，是因为这涉及到概率检验的结果可靠性，我为此查了很多资料，累）。
Goodman I检验公式如下            Goodman II检验检验公式如下
            
注：从统计学原理可知，随着样本量增大，样本均值和总体均值的差误趋向于减少；因此从这两个公式可看出，的值随着样本容量增大而呈几何平方值减小，几乎可以忽略不计算，因此MacKinnon et al. (1998)认为乘积项在样本容量较大时是“trivial”（琐碎不必要的）的，因此sobel检验和Goodman检验结果在大样本情况下区别不大，三个检验公式趋向于一致性结果，因此大家用soble检验公式就可以了（详情请参考文献A Comparison of Methods to Test Mediation and Other Intervening Variable Effects. Psychological Methods
2002, Vol. 7, No. 1, 83–104）。

评价：采用sobel等检验公式对中介效应的检验容易得到中介效应显著性结果，因为其临界概率（MacKinnon）P<.05的Z值为zα/2>0.90或zα/2<-0.90，而正态分布曲线下临界概率P<.05的Z值为zα/2>1.96或zα/2<-1.96，因此用该临界概率表容易犯第一类错误（拒绝虚无假设而作出中介效应显著的判断）

3.差异检验法(difference in coefficients)。此方法同样要找出联合标准误，目前存在一些计算公式，经过MacKinnon等人的分析，认为其中有两个公式效果较好，分别是Clogg 等人和Freedman等人提出的，这两个公式如下：
Clogg差异检验公式            Freedman差异检验公式
               
这两个公式都采用t检验，可以通过t值表直接查出其临界概率。Clogg等提出的检验公式中，的下标N-3表示t检验的自由度为N-3，为自变量与中介变量的相关系数，为X对Y的间接效应估计值的标准误；同理见Freedman检验公式。
评价：这两个公式在a=0且b=0时有较好的检验效果，第一类错误率接近0.05，但当a=0且b≠0时，第一类错误率就非常高有其是Clogg等提出的检验公式在这种情况下第一类错误率达到100%，因此要谨慎对待。

4.温忠麟等提出了一个新的检验中介效应的程序，如下图：

这个程序实际上只采用了依次检验和sobel检验，同时使第一类错误率和第二类错误率都控制在较小的概率，同时还能检验部分中介效应和完全中介效应，值得推荐。

### 在 SPSS 中进行中介效应分析

下面采用Preacher(2004)设计的spssmaro脚本来进行中介效应分析，该脚本是美国俄亥俄和州立大学Preacher和Hayes于2004年开发的在spss中计算间接效应、直接效应和总效应的脚本，对间接效应的计算采用了sobel检验，并给出了显著性检验结果，这个脚本可在如下网址下载：www.comm.ohio-state.edu/ahayes/sobel.htm。
脚本文件名为sobel_spss，关于如何在spss使用该脚本请看附件(附件为pdf文件，文件名为runningscripts)。在运行了脚本后，在打开的窗口中分别输入自变量、中介变量和调节变量，在选项框中可以选择bootstrap（自抽样）次数，设置好后，点击ok，运行结果如下：


### 在 R 中进行中介效应分析





## 调节效应



